#!/bin/sh
# Docker-lane conformance probe (phase 09, §11). Runs ONLY inside the Docker
# sandbox lane's alpine container (busybox sh) — never on the host (§21
# rule 3). Same contract as probe.ts: ONE JSON document on stdin ->
#   { op: 'read'|'write'|'net'|'sleep'|'echo', path?, url?, content?, ms?, value? }
# ONE JSON document on stdout ->
#   { ok, denied, detail, data? }
#
# JSON handling constraint (documented, deliberate): the input is MACHINE-
# generated by the conformance fixture — flat string/number fields, no
# embedded quotes, backslashes, or nesting (fs paths are container-side POSIX
# paths) — so a sed field extractor is safe here. This is a probe, not a JSON
# parser. Output values are fixed detail strings plus test-controlled safe
# data strings, so they are emitted unescaped.
#
# Denial detection (outcome-equivalence, not mechanism-equivalence): in a
# capability-scoped container, out-of-scope paths were simply never mounted
# and with --network none the network does not exist — so ANY operation
# failure reports denied:true. The conformance suite asserts that both lanes
# reach the same allow/deny OUTCOME for the same declaration; the mechanism
# (Deno permission check vs. absent mount/network) legitimately differs.
#
# Always exits 0: the outcome IS the JSON document.

input=$(cat)

field() {
  printf '%s' "$input" | sed -n "s/.*\"$1\":\"\([^\"]*\)\".*/\1/p"
}

numfield() {
  printf '%s' "$input" | sed -n "s/.*\"$1\":\([0-9][0-9]*\).*/\1/p"
}

# emit <ok> <denied> <detail> [data]
emit() {
  if [ "$#" -ge 4 ]; then
    printf '{"ok":%s,"denied":%s,"detail":"%s","data":"%s"}\n' "$1" "$2" "$3" "$4"
  else
    printf '{"ok":%s,"denied":%s,"detail":"%s"}\n' "$1" "$2" "$3"
  fi
}

op=$(field op)

case "$op" in
  read)
    path=$(field path)
    if data=$(cat "$path" 2>/dev/null); then
      emit true false "read ok" "$data"
    else
      emit false true "read failed: path not reachable in this container"
    fi
    ;;
  write)
    path=$(field path)
    content=$(field content)
    if printf '%s' "$content" > "$path" 2>/dev/null; then
      emit true false "write ok"
    else
      emit false true "write failed: path not reachable in this container"
    fi
    ;;
  net)
    url=$(field url)
    # busybox wget: -T <sec> timeout, -q quiet, -O - to stdout. (GNU wget's
    # -t retry flag does not exist in busybox; busybox does not retry.)
    if data=$(wget -T 3 -q -O - "$url" 2>/dev/null); then
      emit true false "net ok" "$data"
    else
      emit false true "net failed: network not reachable in this container"
    fi
    ;;
  sleep)
    ms=$(numfield ms)
    [ -n "$ms" ] || ms=0
    secs=$(( (ms + 999) / 1000 ))
    sleep "$secs"
    emit true false "sleep ok"
    ;;
  echo)
    value=$(field value)
    if [ -z "$value" ]; then
      value=$(numfield value)
    fi
    emit true false "echo ok" "$value"
    ;;
  *)
    emit false false "unknown op: $op"
    ;;
esac

exit 0
